config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :articles, only: [:index, :show]

  namespace :backend do
    resources :articles
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :content
end

app/models/backend/article.rb
class Backend::Article < Article

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < ApplicationController
  http_basic_authenticate_with name: "123", password: "123"

  before_action :get_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Backend::Article.all
  end

  def new
    @article = Backend::Article.new
  end

  def create
    @article = Backend::Article.new(article_params)
    if @article.save
      redirect_to backend_article_path(@article)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to backend_article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy if @article
    redirect_to backend_articles_path
  end

  private
    def get_article
      @article = Backend::Article.find(params[:id])
    end

    def article_params
      params.require(:backend_article).permit(:title, :content)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<h4><%= article.title %></h4>
<div><%= article.content %></div>

<%= link_to "back", articles_path, class: "ui button" %>

app/views/articles/_article_title.html.erb
<div class="ui relaxed divided list">
  <% @articles.each do |article| %>
  <div class="item">
    <i class="caret right icon"></i>
    <div class="content">
      <div class="despcription"> <%= link_to article.title, article_path(article), class: "header" %></div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<h2>Article List</h2>
<%= render 'article_title' %>

app/views/articles/show.html.erb
<%= render @article %>

app/views/backend/articles/_article.html.erb
<h4><%= article.title %></h4>
<div><%= article.content %></div>

<%= link_to "edit", edit_backend_article_path(article) %>
<%= link_to "delete", backend_article_path(article), method: :delete %>

app/views/backend/articles/_form.html.erb
<div>
<%= form_for @article do |f| %>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>

  <div><%= f.text_area :content %></div>
  <%= f.submit %>
<% end %>
</div>

app/views/backend/articles/edit.html.erb
<%= render 'form' %>
<%= link_to "Back", backend_articles_path %>

app/views/backend/articles/index.html.erb
<h2>Admin Article List</h2>
<h4><%= link_to "New Article", new_backend_article_path %></h4>
<%= render @articles %>

app/views/backend/articles/new.html.erb
<%= render "form" %>

app/views/backend/articles/show.html.erb
<%= render @article %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArticlesBase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome RyRoR</h2>
<div><%= link_to "articles list", articles_path %></div>
<div><%= link_to "Admin mode", backend_articles_path %></div>